---
title: "process_sleap_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{process_sleap_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fishmechr)
library(tidyverse)
library(here)
```

```{r}
library(cli)
options(cli.progress_show_after = 0)
options(cli.progress_clear = FALSE)
```

```{r}
sleapfiles <- c(
  here("data","2024-11-14_labels2.000_fish_01-030RPM-ortho-2024-11-14T044441.analysis.csv"),
  here("data","2024-11-14_labels2.001_fish_01-040RPM-ortho-2024-11-14T044525.analysis.csv"),
  here("data", "2024-11-14_labels2.002_fish_01-050RPM-ortho-2024-11-14T045204.analysis.csv"),
  here("data","2024-11-14_labels2.003_fish_01-060RPM-ortho-2024-11-14T044754.analysis.csv"),
  here("data","2024-11-14_labels2.004_fish_01-070RPM-ortho-2024-11-14T044858.analysis.csv")
)

goodframes <- read_csv(here("data", "zfish_goodframes.csv"))

fps <- 50
```

```{r}
parse_file_name <- function(fn)
{
  d <- str_match(fn, 
                 "_(?<id>\\w+_\\d+)-(?<speed>\\d+)RPM.+(?<datetime>\\d{4}-\\d{2}-\\d{2}T\\d{6})")
  
  as_tibble_row(d[1, 2:4], .name_repair = "minimal")
}
```

```{r}
pointnames <- c("snout", "hyoid", "left_eye", "right_eye", "left_pec_fin_base", 
"left_pec_fin_tip", "right_pec_fin_base", "right_pec_fin_tip", "pelvic_fin_base",
"anus", "peduncle", "ventral_caudal", "dorsal_caudal")
```

```{r}
zfdata <- map(sleapfiles, \(fn) read_csv(fn, id = "fn", 
                                         show_col_types = FALSE)) |> 
  bind_rows()
```

```{r}
zfdata <- zfdata |> 
  mutate(dd = map(fn, parse_file_name)) |> 
  unnest(dd) |> 
  mutate(fn = basename(fn),
         speed = as.numeric(speed)) |> 
  relocate(id, speed, datetime) |> 
  pivot_kinematics_longer(pointnames = pointnames)
```

```{r}
zfdata_good <- list()
for (i in seq(1, nrow(goodframes))) {
  good1 <- zfdata |> 
    filter(fn == goodframes$File[[i]],
           between(frame_idx, goodframes$Start[[i]], goodframes$End[[i]])) |> 
    mutate(block = goodframes$Block[[i]])
  zfdata_good[[i]] <- good1
}
zfdata_good <- bind_rows(zfdata_good)
```

```{r}
add_centers <- function(df) {
  r1 <- df[1,] |>
    mutate(point = factor("eye_ctr", levels = levels(df$point)),
          x = mean(df$x[str_detect(df$point, "eye")]),
          y = mean(df$y[str_detect(df$point, "eye")]),
          score = NA)

  r2 <- df[1,] |>
    mutate(point = factor("pec_fin_ctr", levels = levels(df$point)),
          x = mean(df$x[str_detect(df$point, "pec_fin_base")]),
          y = mean(df$y[str_detect(df$point, "pec_fin_base")]),
          score = NA)
  
  df |> 
  add_row(r1) |> 
  add_row(r2)
}
```

```{r}
zfdata_ctr <-
  zfdata_good |> 
  # filter(speed == 30,
  #        frame_idx == 121) |>
  group_by(speed, frame_idx) |>
  mutate(point = fct_expand(point, "eye_ctr", after = 1),
         point = fct_expand(point, "pec_fin_ctr", after = 4)) |> 
  group_modify(\(df, k) add_centers(df))
  # add_centers()
```

```{r}
zfdata_ctr |> 
  arrange(speed, frame_idx, point) |> 
  filter(speed == 30,
         between(frame_idx, 120, 140)) |> 
  filter(point %in% c("snout", "hyoid", "eye_ctr", "pec_fin_ctr", 
                      "pelvic_fin_base", "anus", "peduncle", "ventral_caudal")) |> 
  ggplot(aes(x = x, y = y, color = point)) +
  geom_point() +
  geom_path(aes(group = frame_idx)) +
  coord_fixed()
```

```{r}
zfdata_ctr |> 
  arrange(speed, frame_idx, point) |> 
  filter(speed == 30,
         between(frame_idx, 120, 250)) |> 
  filter(point %in% c("snout", "peduncle", "ventral_caudal")) |> 
  ggplot(aes(x = frame_idx, y = y, color = point)) +
  geom_point() +
  geom_path()
```

```{r}
zfdata_sm <-
  zfdata_ctr |> 
  arrange(speed, frame_idx, point) |> 
  filter(point %in% c("snout", "hyoid", "eye_ctr", "pec_fin_ctr", 
                      "pelvic_fin_base", "anus", "peduncle", "ventral_caudal")) |> 
  # filter(fn == "2024-11-14_labels2.000_fish_01-030RPM-ortho-2024-11-14T044441.analysis.csv",
  #        between(frame_idx, 1, 10)) |>
  group_by(fn, frame_idx) |>
  mutate(arclen0 = arclength(x, y, na.skip = TRUE)) |> 
  interpolate_points_df(arclen0, x, y, spar = 0.2,
                        tailmethod = 'extrapolate',
                        fill_gaps = 1,
                        .frame = frame_idx,
                        .out = c(arclen='arclen', xs='xs', ys='ys')) |> 
  ungroup()
  
```

```{r}
zfdata_sm |> 
  arrange(speed, frame_idx, point) |> 
  filter(speed == 30,
         between(frame_idx, 120, 250)) |> 
  filter(point %in% c("snout", "peduncle", "ventral_caudal")) |> 
  ggplot(aes(x = frame_idx, y = ys, color = point)) +
  geom_point() +
  geom_path()

```

```{r}
zebrafish_shape |> 
  ggplot(aes(x = s)) +
  geom_path(aes(y = width)) +
  geom_path(aes(y = height), color = "blue")
```

```{r}
zfdata_sm <- zfdata_sm |> 
  group_by(id, speed, datetime, frame_idx) |> 
  mutate(width = interpolate_width(zebrafish_shape$s,
                                   zebrafish_shape$width,
                                   arclen),
         height = interpolate_width(zebrafish_shape$s,
                                   zebrafish_shape$height,
                                   arclen)
         )
```

```{r}
zfdata_sm |> 
  filter(speed ==30,
         frame_idx == 150)
```

```{r}
zfdata_split <-
  zfdata_sm |> 
  group_by(id, speed, datetime, block) |> 
  group_split()

zfdata_ctr <- list()
for (i in seq(1, length(zfdata_split))) {
  zfdata_ctr[[i]] <-
    zfdata_split[[i]] |> 
    get_midline_center_df(arclen, xs, ys,
                          width = width, height = height,
                          .frame = frame_idx) |> 
    mutate(xctr = xs - xcom,
           yctr = ys - ycom,
           t = frame_idx / fps) |> 
    get_primary_swimming_axis_df(t, xctr, yctr, 
                                 .frame = frame_idx)
}

zfdata_ctr <- bind_rows(zfdata_ctr)
```

```{r}
zfdata_ctr |> 
  filter(speed == 30,
         block == 1) |> 
         # point %in% c("snout", "ventral_caudal")) |> 
  # filter(between(t, 1, 1.2)) |> 
  ggplot(aes(x = exc_x, y = exc, color = frame_idx)) +
  geom_path(aes(group = frame_idx))
```

```{r}
zfdata_ctr |> 
  filter(speed == 30,
         block == 1,
         point %in% c("snout", "ventral_caudal")) |> 
  # filter(between(t, 1, 1.2)) |> 
  ggplot(aes(x = t, y = exc, color = point)) +
  geom_path()
```

```{r}
zfdata_phase <-
zfdata_ctr |> 
  arrange(id, speed, datetime, frame_idx, desc(point)) |> 
  group_by(id, speed, datetime, point) |> 
  mutate(ph_e = hilbert_phase(exc),
         ph_p = peak_phase(exc))
```

```{r}
zfdata_phase |> 
  filter(speed == 30,
         block == 1) |> 
  ungroup() |> 
  filter(point %in% c("snout", "peduncle", "ventral_caudal")) |> 
  mutate(point = factor(point)) |> 
  pivot_longer(cols = c(ph_e, ph_p), names_to = "method", values_to = "phase") |> 
  ggplot(aes(x = t, y = phase, color = point, linetype = method)) +
  geom_path() + 
  facet_wrap(~point)
```

```{r}
zfdata_phase |> 
  filter(speed == 30,
         block == 1) |> 
  ungroup() |> 
  group_by(point) |> 
  mutate(freq_p = get_frequency(t, ph_p, method='deriv')) |> 
  filter(point %in% c("snout", "peduncle", "ventral_caudal")) |> 
  ggplot(aes(x = t, y = freq_p, color = point)) +
  scale_shape_manual(values = c(1, 17, 22)) +
  geom_point() +
  facet_wrap(~point)
```

```{r}
zfdata_cyc <-
  zfdata_phase |> 
  group_by(id, speed, datetime, block) |> 
  get_body_cycle_numbers_df(ph_p, pointval = "peduncle",
                            .frame = frame_idx) |> 
  arrange(id, speed, datetime, block, t, point)

zfdata_cyc
```

```{r}
zfdata_cyc |> 
  filter(#speed == 30,
         block == 1) |> 
  ungroup() |> 
  group_by(speed, point, cycle) |> 
  summarize(amp = (max(exc) - min(exc)) / 2,
            arclen = mean(arclen)) |> 
  ggplot(aes(x = arclen, y = amp, color = speed)) +
  geom_path(aes(group = cycle))

```

